version: '3.8'

services:
  db:
    image: mysql:latest
    container_name: database1_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: dinosaurio95
      MYSQL_DATABASE: exam
      MYSQL_USER: samy
      MYSQL_PASSWORD: dinosaurio95
    ports:
      - "4600:3306"
    volumes:
      - db_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: database1_adminer
    restart: always
    ports:
      - "8001:8080"

volumes:
  db_data:

